version: '3'
services:

  vsdraw_srv:
    container_name: vsdraw_cnt
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
        PHP_EXTENSION_GD: 1
    volumes:
      - ./app/:/var/www/html/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:80